### ISSUE TITLE
Output types broken as input types InventoryConfigurationOutputTypeDef, LifecycleRuleOutputTypeDef

### ISSUE THREAD

**Issue by sodul** [youtype/mypy_boto3_builder#254]
**Describe the bug**
After upgrading to 1.34.92 (confirmed with 1.34.93) our codebase is getting 2 new mypy errors with:
* `InventoryConfigurationOutputTypeDef` vs `InventoryConfigurationTypeDef`
* `LifecycleRuleOutputTypeDef` vs `LifecycleRuleTypeDef`

**To Reproduce**
Add code that works with the output as input.
InventoryConfigurationOutputTypeDef, LifecycleRuleOutputTypeDef

1. Install `boto3-stubs[s3]`
2. Run `mypy`/`pyright` on the following code sample

```python
from typing import TYPE_CHECKING
import boto3
if TYPE_CHECKING:
    from mypy_boto3_s3 import S3Client
    from mypy_boto3_s3.type_defs import LifecycleRuleOutputTypeDef
    from mypy_boto3_s3.type_defs import LifecycleRuleTypeDef

client: S3Client = boto3.client('s3')
rules = client.get_bucket_lifecycle_configuration(Bucket='bucket_name')['Rules']
new_rule: LifecycleRuleTypeDef = {
    'ID': 'rule_name',
    'Expiration': {'Days': 1},
    'Filter': {'Prefix': 'prefix'},
    'NoncurrentVersionExpiration': {'NoncurrentDays': 1},
    'AbortIncompleteMultipartUpload': {'DaysAfterInitiation': 1},
    'Status': 'Enabled',
}
rules.append(new_rule)
```

**Actual output**

```
> mypy s3.py
s3.py:18: error: Argument 1 to "append" of "list" has incompatible type "LifecycleRuleTypeDef"; expected "LifecycleRuleOutputTypeDef"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

**Expected output**

no error

**Additional context**
Your OS macOS and linux, `boto3-stubs` installation method, `boto3` version, etc.

Relates to #208

**Comment by vemel** [comment]
Hello! THank you for the report.

Looks like this output type is not compatible with the corresponding input type. I will take a look.

**Comment by vemel** [comment]
Unfortunately, these types are incompatible. Does rewriting code as 

```python
new_rule: LifecycleRuleOutputTypeDef = {
    'ID': 'rule_name',
    'Expiration': {'Days': 1},
    'Filter': {'Prefix': 'prefix'},
    'NoncurrentVersionExpiration': {'NoncurrentDays': 1},
    'AbortIncompleteMultipartUpload': {'DaysAfterInitiation': 1},
    'Status': 'Enabled',
}
```

work for you?

**Comment by sodul** [comment]
It does not seem to help. We are going to use `# type: ignore` for now:
```
rules: list[LifecycleRuleTypeDef]
rules = client.get_bucket_lifecycle_configuration( # type: ignore[assignment]
    Bucket='bucket_name'
)['Rules']
```

**Comment by vemel** [comment]
As far as I understand, before you used `mypy-boto3-s3 1.34.65`. There was a bug fixed in #244 that incompatible output shapes were used instead of separating output and input shapes in case of conflict.

For this particular shape input and output definitions are not compatible. So, `type: ignore` looks like the easiest solution.

`pyright` changes the way it compares TypedDicts in https://github.com/microsoft/pyright/releases/tag/1.1.333 release. So, since TypedDicts are invariant, output TypedDict cannot be assigned to an input TypedDict.

I will cross-check again tomorrow.

**Comment by vemel** [comment]
Closing this issue because current behavior is intended. Let me know if you still have any issues.
